server:
  port: 8083

spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3307/ko_ride_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

# Optional: logging SQL
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE