server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ko_ride_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/ko_ride  # If you're using MongoDB

  kafka:
    bootstrap-servers: localhost:9092

# Optional: logging SQL
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

event:
  notification:
    topics:
      trip-request: ride.requests
      ride-accepted: ride.accepted
      ride-completed: ride.completed
      payment-initiated: payment.initiated
