server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ko_ride_db
    username: root
    password: your_mysql_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

